name: tedarikten
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2
  firebase_core: ^2.8.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.10
  shared_preferences: ^2.2.0
  intl: any
  mockito: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/

  fonts:
    - family: FontNormal
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: FontBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf