name: tedarikten
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: FontNormal
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: FontBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf